image:
  repository: openftth/mbtileserver
  tag: v0.7.0

storage:
  enabled: true
  size: 1Gi
  className: ""
  path: /data

reload:
  image: openftth/mbtileserver-watcher
  tag: v1.0.0
  enabled: true
  watchPath: /data

service:
  externalPort: 80
  type: LoadBalancer

commandArgs:
  - "--enable-reload-signal"
  - "-d"
  - "/data"
