apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteMany
  {{ if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
